# Generated by Django 6.0.1 on 2026-03-03 14:10

import Aplicaciones.sbr_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app', '0028_movimientocaja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientocaja',
            name='registrado_por',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='plano',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='cuota_origen',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='es_entrada',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='numero_transaccion',
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mora_grave_dias',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mora_grave_valor',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mora_leve_dias',
            field=models.IntegerField(default=5, help_text='Días para aplicar primera mora'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mora_leve_valor',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mora_media_dias',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mora_media_valor',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lote',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto del lote (opcional)', null=True, upload_to='lotes/', validators=[Aplicaciones.sbr_app.validators.validar_archivo_seguro]),
        ),
        migrations.DeleteModel(
            name='DetallePago',
        ),
        migrations.DeleteModel(
            name='MovimientoCaja',
        ),
    ]
