# Generated by Django 6.0.1 on 2026-03-03 14:21

import Aplicaciones.sbr_app.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app', '0029_remove_movimientocaja_registrado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='mora_grave_dias',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='mora_grave_valor',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='mora_leve_dias',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='mora_leve_valor',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='mora_media_dias',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='mora_media_valor',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='imagen',
        ),
        migrations.AddField(
            model_name='lote',
            name='plano',
            field=models.ImageField(blank=True, help_text='Imagen del plano/mapa del lote', null=True, upload_to='lotes/planos/', validators=[Aplicaciones.sbr_app.validators.validar_archivo_seguro]),
        ),
        migrations.AddField(
            model_name='pago',
            name='cuota_origen',
            field=models.ForeignKey(blank=True, help_text='Si seleccionó una cuota intencionalmente al pagar, este campo la guarda para recordarlo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sbr_app.cuota'),
        ),
        migrations.AddField(
            model_name='pago',
            name='es_entrada',
            field=models.BooleanField(default=False, help_text='Indica si este pago corresponde a la cuota de entrada no amortizable'),
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_transaccion',
            field=models.IntegerField(blank=True, help_text='Número secuencial del pago dentro del contrato', null=True),
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, help_text='Monto de este pago destinado a esta cuota', max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_asociados', to='sbr_app.cuota')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sbr_app.pago')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
