# Generated by Django 6.0.1 on 2026-05-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app', '0030_remove_configuracionsistema_mora_grave_dias_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('manzana', 'numero_lote')},
        ),
    ]
